---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# coralmz (In Development)
Coralmz is an R package that contains a table of coral mass spectral features
and a primitive function to search it. All features have been identified
either in coral or closely related organisms such as their symbionts. All
features were obtained from peer reviewed research articles (referenced within
the table) and have, as a minimum, a level 1 metabolite identification according to
the Proposed Minimum Reporting Standards for Chemical Analysis (Sumner et al. 2007).

For more information about the package please see the
package [DESCRIPTION](DESCRIPTION).

### Usage

You can install this released version of coralmz as a package in R using the
devtools package:

``` r
devtools::install_github("brgordon17/coralmz")
```

Alternatively, the table can be downloaded as either a `.csv` file or an `.rda` 
file from from the `/data` directory [here](/data).

### How to Contribute
If you are a GitHub user and would like to contribute to the database you can 
[open an issue](https://help.github.com/en/articles/creating-an-issue)
and give me your suggestions, or 
[fork this repository](https://help.github.com/en/articles/fork-a-repo)
and create a 
[pull request](https://help.github.com/en/articles/creating-a-pull-request). Alternatively, I can be contacted at brgordon17@gmail.com.

### License
Creative Commons Attribution 4.0 International Public License

For more information, please see the [LICENSE](LICENSE.md) file.
